# Generated by Django 5.1 on 2024-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='published_date',
            field=models.DateField(),
        ),
    ]
