# Generated by Django 5.1 on 2024-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='type',
            field=models.CharField(choices=[('cbt', 'Cognitive Behavioral Therapy (CBT)'), ('dbt', 'Dialectical Behavior Therapy (DBT)'), ('mbct', 'Mindfulness-Based Cognitive Therapy (MBCT)'), ('act', 'Acceptance and Commitment Therapy (ACT)'), ('exposure', 'Exposure Therapy'), ('family', 'Family Therapy'), ('sfbf', 'Solution-Focused Brief Therapy (SFBT)'), ('art', 'Art Therapy'), ('tf_cbt', 'Trauma-Focused Cognitive Behavioral Therapy (TF-CBT)'), ('schema', 'Schema Therapy')], max_length=50),
        ),
    ]
