# Generated by Django 5.1 on 2024-09-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('current_fill', models.IntegerField()),
                ('bin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage_app.bintype')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateTimeField()),
                ('collected_amount', models.IntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage_app.bin')),
            ],
        ),
    ]
