# Generated by Django 5.1 on 2024-09-19 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionschedule',
            options={'ordering': ['collection_date']},
        ),
        migrations.RenameField(
            model_name='bin',
            old_name='bin_type',
            new_name='bintype',
        ),
        migrations.AddField(
            model_name='bintype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='capacity',
            field=models.IntegerField(help_text='Capacity in litres'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='current_fill',
            field=models.IntegerField(help_text='Current fill in litres'),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='collected_amount',
            field=models.IntegerField(default=0, help_text='Collected amount in litres'),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage_app.bin')),
            ],
        ),
    ]
