# Generated by Django 5.1 on 2024-08-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagebin',
            name='current_level',
        ),
        migrations.AddField(
            model_name='garbagebin',
            name='current_fill',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage_app.garbagebin')),
            ],
        ),
    ]
