# Generated by Django 5.1 on 2024-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_app', '0002_remove_garbagebin_current_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionschedule',
            name='collected_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collectionschedule',
            name='collection_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='garbagebin',
            name='current_fill',
            field=models.IntegerField(),
        ),
    ]
