# Generated by Django 5.1 on 2024-08-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_app', '0003_collectionschedule_collected_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GarbageBin',
            new_name='Bin',
        ),
    ]
